# aiops-worker-access-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: worker-aiops-access-role
rules:
- apiGroups: ["aiops.kubeslice.io"]
  resources:
    - workerclustergpuallocations
    - workerslicegpuprovisioningrequests
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["aiops.kubeslice.io"]
  resources:
    - workerclustergpuallocations/status
    - workerslicegpuprovisioningrequests/status
  verbs: ["get", "update", "patch"]

---
# aiops-worker-access-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: worker-aiops-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: worker-aiops-access-role
subjects:
- kind: ServiceAccount
  name: kubeslice-rbac-worker-trg-nkp-wkl-001
  namespace: kubeslice-avesha