apiVersion: v1
data:
  endpoint: aHR0cHM6Ly91aS5rdWJlc2xpY2UudHJn
  namespace: a3ViZXNsaWNlLWNvbnRyb2xsZXI=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluVlBVVzgwYm14NFdteHhXbmN3WkdFd2NYSmliV1pJZFVvMFdGaFRVMWszZVRWTllTMXViRVJDZGswaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbGMyeHBZMlV0WVhabGMyaGhJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbXQxWW1WemJHbGpaUzF5WW1GakxYSjNMV0ZrYldsdUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkltdDFZbVZ6YkdsalpTMXlZbUZqTFhKM0xXRmtiV2x1SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pWWpFMU5qRXhaVGd0WlRCak5TMDBNVGxrTFRsaFpHWXRNVFF6T1dJeFpUVmhZV0ZsSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tdDFZbVZ6YkdsalpTMWhkbVZ6YUdFNmEzVmlaWE5zYVdObExYSmlZV010Y25jdFlXUnRhVzRpZlEuWnp0eFNJWWxpWTdocHlfZVl6OW5QSWlGelg0dzdNb2xkY2U2c2wzTkFLdEpKQm51QV9ZMDBuemk1eDVGdk92UnFNVWZ1MWZ4cG5oVVRBM0xuUEFlZlI3c21XbDRSX184Wnp6dURIOEh2QVlRQm1KendsT1ZKY01zb0Y0V2pUVWx6eS1xWThfUHpOeXVMR0JPSG51YzFZdW93cndpTmFtb3FrUG5KYjN2ZVJpYndUZkZhdTV2T2Y3clB1UjNMcUlsX05MUl9MaV9FSktFREprTkI4X05DZUtRcUlOcERIZEdjZ01DeTQ1SWNKV093U2pIM09jb1NyZ3RWVGhYVUVlN1FuUXdMUk43akxEYnZxM2VXWFZQWkZFVTE0M0ZxbHN2RTN1QzZDQmp5ZUxPbUxfNWdDUUhNR1pnUWJpVEJpZ1BhM3d1TEZkS0QyZTJnNV9SME1RSG1R
stringData:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIBbjCCARWgAwIBAgIRAIbtBOnHzSb4BHq437YvDgwwCgYIKoZIzj0EAwIwFzEV
    MBMGA1UEAxMMa29tbWFuZGVyLWNhMB4XDTI1MDkxMDA5Mzg1NVoXDTI1MTIwOTA5
    Mzg1NVowFzEVMBMGA1UEAxMMa29tbWFuZGVyLWNhMFkwEwYHKoZIzj0CAQYIKoZI
    zj0DAQcDQgAEm44FysylpAiS+zCHr5gFOc/PDAJpwYCoPbNgZjClcIg8nsm7A8KF
    q4nYflJAnKbUydg5TJVKkne/YjS0dxGbIKNCMEAwDgYDVR0PAQH/BAQDAgKkMA8G
    A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFErxKsiCO6brK0elNi2p8WY/4CV4MAoG
    CCqGSM49BAMCA0cAMEQCIBR0gsDCQacYXv/OxDAIQOkv2XiuXiTWDiuBd3Op2zS4
    AiBqPouGVxT9r2B3sdxt+Y2Bh8PFaJ0tYVKKZGbqRKnh5g==
    -----END CERTIFICATE-----
kind: Secret
metadata:
  creationTimestamp: null
  name: kubeslice-controller-secret
  namespace: kubeslice-system
  
  

