apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: trg
  app: kubeslice
resources:
  # - kubeslice-worker-namespace.yaml
  - helm_repo.yaml
  - helm_release.yaml
  - additional-kubeslice-hub-for-aiops-operator.yaml #For some reason hub-secret not created
  - additional-cluster-role-and-binding-for-kubeslice-operator.yaml #For some reason rbac for kubeslice-rbac-worker not created
  - nexus-registry-secret.yaml
  - additional-for-aioperator-rolebinding.yaml
configMapGenerator:
  - name: kubeslice-worker-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml