apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: egs-monitoring
spec:
  interval: 1m
  chart: 
    spec:
      chart: kube-prometheus-stack
      version: 78.4.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: egs-monitoring
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values