apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeslice-controller
  namespace: avesha-trg
spec:
  interval: 1m
  chart: 
    spec:
      chart: kubeslice-controller
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: kubeslice-controller 
        namespace: avesha-trg
  valuesFrom:
    - kind: ConfigMap
      name: kubeslice-controller-values