apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovLzE3Mi4xNi4xMDkuMTY4Ijp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IlBAc3N3MHJkMTIzNDU2IiwiYXV0aCI6IllXUnRhVzQ2VUVCemMzY3djbVF4TWpNME5UWT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: nexus-registry-secret
  namespace: kubeslice-controller
type: kubernetes.io/dockerconfigjson