global:
  imageRegistry: 172.16.109.168:8081/docker-host/aveshasystems
  # user can configure labels or annotations that EGS Controller namespaces should have
  namespaceConfig:
    labels: {}
    annotations: {}
  kubeTally:
    enabled: false # need postgress avaialble for true
    postgresSecretName: POSTGRES_SECRET_NAME
    postgresAddr: POSTGRES_ADDR
    postgresPort: POSTGRES_PORT
    postgresUser: POSTGRES_USER
    postgresPassword: POSTGRES_PASSWORD
    postgresDB: POSTGRES_DB
    postgresSslmode: POSTGRES_SSLMODE
    prometheusUrl: PROMETHEUS_ENDPOINT
kubeslice:
  controller:
    endpoint: CONTROLLER_ENDPOINT