apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeslice-ui
  namespace: kubeslice-ui
spec:
  interval: 1m
  chart: 
    spec:
      chart: kubeslice-ui
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: kubeslice-ui 
        namespace: kubeslice-ui
  valuesFrom:
    - kind: ConfigMap
      name: kubeslice-ui-values