apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: trg
  app: kubeslice
resources:
  - kubeslice-ui-namespace.yaml
  - helm_repo.yaml
  - helm_release.yaml
  - license.yaml
  - nexus-registry-secret.yaml
  - ui-proxy-tls-secret.yaml
  - certificate.yaml
configMapGenerator:
  - name: kubeslice-ui-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml